### ISSUE TITLE
Increasing latestArticles count limit

### ISSUE THREAD

**Issue by harinij** [sebsojeda/gatsby-theme-purist#2]
Great theme and I am experimenting using this for my blog. Is there an easy way to increase the limit for latestArticles from 2 to a custom number, couldn't find if this was possible in the config file override?

```
latestArticles: allMdx(
      filter: {
        fileAbsolutePath: { regex: "/content/" }
        fields: { draft: { ne: true } }
      }
      limit: 2
      sort: { fields: [frontmatter___date], order: DESC }
    )

**Comment by sebsojeda** [comment]
Hi @harinij, I've added this option to the configuration. Let me know if this helps:

```js
{
      resolve: 'gatsby-theme-purist',
      options: {
        featuredArticleLimit: 2,
      },
 },
```

I've added it to the README here: https://github.com/sebsojeda/gatsby-theme-purist/blob/main/README.md#theme-options

**Comment by harinij** [comment]
Works perfectly. Thanks 👍
